#
#  BUILD
#
#  Copyright 2024 Pepe Unlimited
#  Licensed under the MIT license, see associated LICENSE file for terms.
#  See AUTHORS file for the list of project authors.
#

py_test(
    name = "unittest_test",
    srcs = ["unittest_test.py"],
    main = "unittest_test.py",
    timeout = "short",
    deps = [
        "//src/lib:lib",
    ],
)
